// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return windows;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return windows;
      case TargetPlatform.iOS:
        return windows;
      case TargetPlatform.macOS:
        return windows;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8SvVWuePImsFy_ju46BQkriCsQaVRPcc',
    appId: '1:913193457524:web:669d9ef797412d184f3e21',
    messagingSenderId: '913193457524',
    projectId: 'cafee-finder',
    authDomain: 'cafee-finder.firebaseapp.com',
    storageBucket: 'cafee-finder.firebasestorage.app',
    measurementId: 'G-BDVXDZF19K',
  );
}
